<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report['title'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 4px; }
        h2 { font-size: 12px; margin: 0 0 12px; color: #374151; font-weight: normal; }
        .meta { margin-bottom: 12px; color: #4b5563; }
        .filters { margin-bottom: 12px; padding: 8px; border: 1px solid #e5e7eb; background: #f9fafb; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d1d5db; padding: 5px; vertical-align: top; }
        th { background: #f3f4f6; font-weight: bold; text-align: left; }
        .muted { color: #6b7280; }
    </style>
</head>
<body>
    <h1>Right to Care Zambia</h1>
    <h2>People & Culture Records Management System</h2>

    <div class="meta">
        <strong>{{ $report['title'] }}</strong><br>
        Generated by {{ $generatedBy->name }} on {{ $generatedAt->format('d M Y H:i') }}
    </div>

    <div class="filters">
        <strong>Applied filters:</strong>
        @forelse ($filterSummary as $label => $value)
            <span>{{ ucwords($label) }}: {{ $value }}</span>@if (! $loop->last); @endif
        @empty
            <span class="muted">No filters applied.</span>
        @endforelse
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($report['columns'] as $label)
                    <th>{{ $label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach (array_keys($report['columns']) as $key)
                        <td>{{ $row[$key] ?? '-' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($report['columns']) }}">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
