<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Audit Logs Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 4px; }
        h2 { font-size: 12px; margin: 16px 0 6px; }
        .muted { color: #4b5563; }
        .meta { margin-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d1d5db; padding: 5px; vertical-align: top; }
        th { background: #eef2f7; text-align: left; font-weight: bold; }
        .filters td:first-child { width: 22%; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Right to Care Zambia / People & Culture</h1>
    <div class="meta muted">
        <div><strong>Report:</strong> Audit Logs Report</div>
        <div><strong>Generated By:</strong> {{ $generatedBy->name }} - {{ $generatedBy->email }}</div>
        <div><strong>Generated At:</strong> {{ $generatedAt->format('d M Y H:i') }}</div>
        <div><strong>Records:</strong> {{ $activities->count() }}</div>
    </div>

    <h2>Applied Filters</h2>
    <table class="filters">
        <tbody>
            @forelse ($filterSummary as $label => $value)
                <tr>
                    <td>{{ $label }}</td>
                    <td>{{ $value }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No filters applied.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <h2>Audit Trail</h2>
    <table>
        <thead>
            <tr>
                <th>Date / Time</th>
                <th>Actor</th>
                <th>Module</th>
                <th>Action</th>
                <th>Related Record</th>
                <th>Location</th>
                <th>Description</th>
                <th>IP Address</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($activities as $activity)
                <tr>
                    <td>{{ $activity->created_at->format('d M Y H:i') }}</td>
                    <td>{{ $activity->actor_name }}</td>
                    <td>{{ $activity->module_label }}</td>
                    <td>{{ $activity->display_action }}</td>
                    <td>{{ $activity->subject_label ?? '-' }}</td>
                    <td>{{ $activity->location_label ?? '-' }}</td>
                    <td>
                        {{ $activity->description }}
                        @if ($activity->readable_properties)
                            <br>
                            <span class="muted">
                                @foreach ($activity->readable_properties as $label => $value)
                                    {{ $label }}: {{ $value }}@if (! $loop->last); @endif
                                @endforeach
                            </span>
                        @endif
                    </td>
                    <td>{{ $activity->ip_address ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8">No audit log records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @if ($activities->count() >= 1000)
        <p class="muted">This PDF is limited to the latest 1000 matching audit log records. Apply narrower filters for a smaller audit extract.</p>
    @endif
</body>
</html>
