<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $plan->title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #111827; }
        h1 { font-size: 18px; margin: 0 0 4px; }
        h2 { font-size: 12px; margin: 0 0 12px; color: #374151; font-weight: normal; }
        .meta, .summary { margin-bottom: 12px; }
        .summary span { display: inline-block; margin-right: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #d1d5db; padding: 5px; vertical-align: top; }
        th { background: #f3f4f6; text-align: left; }
    </style>
</head>
<body>
    <h1>Right to Care Zambia</h1>
    <h2>People & Culture Records Management System</h2>

    <div class="meta">
        <strong>{{ $plan->title }}</strong><br>
        Reference: {{ $plan->reference_no }}<br>
        Project: {{ $plan->project?->name ?? 'All projects' }}<br>
        Effective: {{ $plan->effective_month?->format('M Y') }}<br>
        Generated by {{ $generatedBy->name }} on {{ $generatedAt->format('d M Y H:i') }}
    </div>

    <div class="summary">
        <span><strong>Budgeted:</strong> {{ $summary['budgeted'] }}</span>
        <span><strong>Filled:</strong> {{ $summary['filled'] }}</span>
        <span><strong>Vacant:</strong> {{ $summary['vacant'] }}</span>
        <span><strong>Overstaffed:</strong> {{ $summary['overstaffed'] }}</span>
        <span><strong>Vacancy Rate:</strong> {{ $summary['vacancy_rate'] }}%</span>
    </div>

    <table>
        <thead>
            <tr>
                <th>Job Title</th>
                <th>Project</th>
                <th>Department</th>
                <th>Province</th>
                <th>District</th>
                <th>Facility</th>
                <th>Budgeted</th>
                <th>Filled</th>
                <th>Vacant</th>
                <th>Overstaffed</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    <td>{{ $row['job_title'] }}</td>
                    <td>{{ $row['project'] }}</td>
                    <td>{{ $row['department'] }}</td>
                    <td>{{ $row['province'] }}</td>
                    <td>{{ $row['district'] }}</td>
                    <td>{{ $row['facility'] }}</td>
                    <td>{{ $row['budgeted'] }}</td>
                    <td>{{ $row['filled'] }}</td>
                    <td>{{ $row['vacant'] }}</td>
                    <td>{{ $row['overstaffed'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
